### ISSUE TITLE
Fails to compile on Arch Linux: error: ‘EOrbit’ undeclared

### ISSUE THREAD

**Issue by Joaqim** [SanderMertens/ecs_solar#1]
./src/main.c: In function ‘create_planet’:
/home/jq/bake/include/flecs.h:1963:26:error: ‘EEOrbit’ undeclared (first use in this function); did you mean ‘EOrbit’?
`#define ecs_entity(type) E##type`
Specifically this line in main.c:create_planets:
`ecs_set(world, p, Orbit, {orbit_radius, t, .v = speed});`

and in main.c:InitOrbit:
`ecs_entity_t parent = ecs_get_parent(rows->world, rows->entities[0], EOrbit);`

./src/main.c: In function ‘InitOrbit’:
/home/jq/bake/include/flecs.h:1963:26: error: ‘EEOrbit’ undeclared (first use in this function); did
you mean ‘EOrbit’?
`#define ecs_entity(type) E##type`

[Pastebin Log](https://pastebin.com/raw/ZTXuCcsX)

**Comment by SanderMertens** [comment]
Nice catch! Just checked in a fix, it should work again now.

**Comment by Joaqim** [comment]
Trying to close Issue as solved : S

**Comment by Joaqim** [comment]
Feel free to delete this Issue now that it is resolved  ^ ^, sorry for the mess.
